name: PR
on: pull_request

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run linting
        run: npm run lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run tests
        run: npm run test:ci
  build:
    name: Run build step
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run build
        run: npm run build
